name: Hello World Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello, World! Docker Action
        uses: ./hello-world-docker-action/
        with:
          who-to-greet: "GitHub"